train:
    target_path: /yourpath/vertex_cover/rb200/dataset/trainset
    data_dir: /yourpath/vertex_cover/rb200/dataset/trainset

val:
    target_path: /yourpath/vertex_cover/rb200/dataset/valset
    data_dir: /yourpath/vertex_cover/rb200/dataset/valset

test:
    target_path: /yourpath/vertex_cover/rb200/dataset/testset
    data_dir: /yourpath/vertex_cover/rb200/dataset/testset